#!/usr/bin/env bash
# tools/protocol-zero.sh
# Protocol Zero Enforcement: Commit Message Attribution Scanner
#
# Validates commit messages for forbidden AI attribution markers.
# Returns exit code 0 on success, 1 on violation detection.
#
# Usage:
#   ./tools/protocol-zero.sh --commit-msg "message"   # Validate commit message
#   ./tools/protocol-zero.sh --commit-msg-file path   # Validate from file (git hook)

set -euo pipefail

# Color definitions (ANSI escape codes)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# Prohibited patterns (case-insensitive matching)
# These patterns indicate AI attribution that violates Protocol Zero
PROHIBITED_PATTERNS=(
    "generated by claude"
    "generated by ai"
    "generated by copilot"
    "generated by gpt"
    "generated by chatgpt"
    "generated by llm"
    "ai.assisted"
    "ai-assisted"
    "ai assisted"
    "ai generated"
    "ai-generated"
    "created with ai"
    "created by ai"
    "written by ai"
    "written by claude"
    "co-authored-by:.*claude"
    "co-authored-by:.*copilot"
    "co-authored-by:.*ai"
    "co-authored-by:.*anthropic"
    "co-authored-by:.*openai"
    "i hope this helps"
    "as requested"
    "here is the code"
    "here is the readme"
    "as an ai"
    "as a language model"
    "i'm an ai"
    "i am an ai"
    "i have added"
    "updated profile"
)

# No files are scanned - commit message validation only
# README.md excluded as it may contain legitimate AI references

# Track violations
VIOLATIONS_FOUND=0
VIOLATION_DETAILS=()

# Print functions
print_pass() {
    echo -e "${GREEN}${BOLD}[PASS]${NC} ${GREEN}$1${NC}"
}

print_fail() {
    echo -e "${RED}${BOLD}[FAIL]${NC} ${RED}$1${NC}"
}

print_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_info() {
    echo -e "[INFO] $1"
}

print_violation() {
    local file="$1"
    local line_num="$2"
    local content="$3"
    local pattern="$4"
    echo -e "  ${RED}├─${NC} ${BOLD}$file${NC}:${line_num}"
    echo -e "  │  Pattern: ${YELLOW}$pattern${NC}"
    echo -e "  │  Content: ${content:0:80}"
}

# Scan a single text string for violations
# Returns 0 (success/true) if violations found, 1 (failure/false) if clean
scan_text() {
    local text="$1"
    local source="${2:-stdin}"
    local found=1  # 1 = no violations found (false in bash)

    for pattern in "${PROHIBITED_PATTERNS[@]}"; do
        if echo "$text" | grep -iEq "$pattern"; then
            found=0  # 0 = violation found (true in bash)
            VIOLATIONS_FOUND=1
            local match
            match=$(echo "$text" | grep -iE "$pattern" | head -1)
            VIOLATION_DETAILS+=("Source: $source | Pattern: $pattern | Match: ${match:0:60}")
        fi
    done

    return $found
}

# Scan commit message
scan_commit_message() {
    local message="$1"

    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "Protocol Zero: Commit Message Validation"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    if scan_text "$message" "commit-message"; then
        print_fail "Protocol Zero Violation Detected in Commit Message!"
        echo ""
        echo -e "${RED}${BOLD}Violations:${NC}"
        for detail in "${VIOLATION_DETAILS[@]}"; do
            echo -e "  ${RED}├─${NC} $detail"
        done
        echo ""
        echo -e "${YELLOW}${BOLD}Action Required:${NC} Remove attribution before proceeding."
        echo ""
        return 1
    else
        print_pass "Protocol Zero: Commit message is compliant."
        return 0
    fi
}

# Show usage info
show_usage() {
    echo "Protocol Zero Enforcement Script (Profile Repo)"
    echo ""
    echo "Usage:"
    echo "  $0 --commit-msg \"message\"    Validate commit message"
    echo "  $0 --commit-msg-file <path>  Validate commit message from file"
    echo ""
    echo "Exit Codes:"
    echo "  0  No violations detected"
    echo "  1  Violation(s) detected"
}

# Main entry point
main() {
    local mode=""
    local commit_msg=""
    local commit_msg_file=""

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --commit-msg)
                mode="commit"
                commit_msg="$2"
                shift 2
                ;;
            --commit-msg-file)
                mode="commit-file"
                commit_msg_file="$2"
                shift 2
                ;;
            --help|-h)
                show_usage
                exit 0
                ;;
            *)
                print_warning "Unknown argument: $1"
                shift
                ;;
        esac
    done

    # Require a mode
    if [[ -z "$mode" ]]; then
        show_usage
        exit 1
    fi

    # Execute appropriate scan
    case $mode in
        commit)
            scan_commit_message "$commit_msg"
            ;;
        commit-file)
            if [[ ! -f "$commit_msg_file" ]]; then
                print_fail "Commit message file not found: $commit_msg_file"
                exit 1
            fi
            local msg
            msg=$(cat "$commit_msg_file")
            scan_commit_message "$msg"
            ;;
    esac
}

main "$@"
